window.GAME_V2_WORDS_CONFIG = {
  menuUrl: "../index.html",
  waterYRatio: 0.82,
  splashYOffset: 120,
  answerLockMs: 120,
  layout: {
    answers: {
      type: "FourLargeCards",
      content: "image",
      count: 4,
      activeCount: 4,
      minButtonSize: 96,
      maxButtonSize: 210,
      aspectRatio: 1
    }
  },
  assets: {
    splashSheet: { url: "../shared/assets/fx/splash_sheet.png", sheetW: 1024, sheetH: 1024, cols: 4, rows: 4, frames: 16, fps: 30, scale: 0.75 },
    burstSheet: { url: "../shared/assets/fx/burst_sheet.png", sheetW: 1024, sheetH: 1024, cols: 4, rows: 4, frames: 16, fps: 30, scale: 0.65 },
    mascotSheet: { url: "../shared/assets/mascot/kittydance.png", cols: 4, rows: 2, frames: 8, fps: 6 },
    mascotSadSheet: { url: "../shared/assets/mascot/kittysad.png", cols: 4, rows: 2, frames: 8, fps: 6 },
    splashAudio: "../shared/assets/audio/splash.mp3",
    coinAudio: "../shared/assets/audio/coin_drop.mp3",
    emojiTsv: "data/emojis-new/icon-pack-manifest.tsv",
    emojiDir: "data/emojis-new"
  },
  fallbackEmojis: [
    { id: "animal-cat", filename: "animal-cat.png", he: "חתול" },
    { id: "animal-dog", filename: "animal-dog.png", he: "כלב" },
    { id: "animal-rabbit", filename: "animal-rabbit.png", he: "ארנב" },
    { id: "reptile_amphibian_sea_insect-snake", filename: "reptile_amphibian_sea_insect-snake.png", he: "נחש" },
    { id: "reptile_amphibian_sea_insect-dolphin", filename: "reptile_amphibian_sea_insect-dolphin.png", he: "דולפין" },
    { id: "bird-penguin", filename: "bird-penguin.png", he: "פינגווין" },
    { id: "bird-rooster", filename: "bird-rooster.png", he: "תרנגול" },
    { id: "transport-airplane", filename: "transport-airplane.png", he: "מטוס" }
  ],
  difficulties: {
    easy: {
      label: "Easy",
      maxFrequency: 1,
      maxWordLength: 3,
      minWordLength: 2,
      wordPool: {
        excludedCategories: ["legacy"],
        preferredOnlyMinPool: 15,
        preferredIds: [
          "animal-dog",
          "animal-fox",
          "animal-cat",
          "animal-cow",
          "animal-pig",
          "animal-ox",
          "animal-ram",
          "bird-owl",
          "reptile_amphibian_sea_insect-bug",
          "reptile_amphibian_sea_insect-ant",
          "food_plant_kitchen-egg",
          "nature_weather-sun",
          "school_play-pen",
          "kitchen_household-cup",
          "kitchen_household-mug",
          "places_city_objects-key",
          "places_city_objects-tv",
          "places_city_objects-box",
          "clothing-hat",
          "home_furniture_bathroom-bed"
        ]
      },
      distractors: {
        minSimilarityScore: 0,
        maxSimilarityScore: 1,
        minLengthDelta: 2,
        allowSameFirstLetter: false,
        allowSameLastLetter: false
      }
    },
    medium: {
      label: "Medium",
      maxFrequency: 2,
      maxWordLength: 5,
      minWordLength: 3,
      wordPool: {
        excludedCategories: ["legacy"],
        preferredOnlyMinPool: 40,
        preferredIds: [
          "animal-dog",
          "animal-wolf",
          "animal-fox",
          "animal-cat",
          "animal-lion",
          "animal-tiger",
          "animal-moose",
          "animal-horse",
          "animal-zebra",
          "animal-deer",
          "animal-bison",
          "animal-ox",
          "animal-cow",
          "animal-pig",
          "animal-ram",
          "animal-goat",
          "animal-camel",
          "animal-llama",
          "animal-mouse",
          "animal-rat",
          "animal-rabbit",
          "animal-bear",
          "animal-koala",
          "animal-panda",
          "animal-otter",
          "animal-skunk",
          "bird-bird",
          "bird-duck",
          "bird-swan",
          "bird-owl",
          "bird-eagle",
          "bird-goose",
          "bird-dove",
          "bird-parrot",
          "bird-chicken",
          "bird-turkey",
          "reptile_amphibian_sea_insect-frog",
          "reptile_amphibian_sea_insect-turtle",
          "reptile_amphibian_sea_insect-snake",
          "reptile_amphibian_sea_insect-whale",
          "reptile_amphibian_sea_insect-shark",
          "reptile_amphibian_sea_insect-crab",
          "reptile_amphibian_sea_insect-shrimp",
          "reptile_amphibian_sea_insect-snail",
          "reptile_amphibian_sea_insect-butterfly",
          "reptile_amphibian_sea_insect-ant",
          "reptile_amphibian_sea_insect-bug",
          "reptile_amphibian_sea_insect-beetle",
          "reptile_amphibian_sea_insect-honeybee",
          "reptile_amphibian_sea_insect-spider",
          "food_plant_kitchen-grapes",
          "food_plant_kitchen-melon",
          "food_plant_kitchen-lemon",
          "food_plant_kitchen-banana",
          "food_plant_kitchen-pear",
          "food_plant_kitchen-peach",
          "food_plant_kitchen-tomato",
          "food_plant_kitchen-bread",
          "food_plant_kitchen-bagel",
          "food_plant_kitchen-waffle",
          "food_plant_kitchen-bacon",
          "food_plant_kitchen-pizza",
          "food_plant_kitchen-taco",
          "food_plant_kitchen-egg",
          "food_plant_kitchen-salt",
          "food_plant_kitchen-sushi",
          "food_plant_kitchen-cookie",
          "food_plant_kitchen-candy",
          "food_plant_kitchen-teapot",
          "food_plant_kitchen-spoon",
          "food_plant_kitchen-apple_red",
          "food_plant_kitchen-onion",
          "food_plant_kitchen-rice",
          "food_plant_kitchen-soup",
          "transport-train",
          "transport-metro",
          "transport-tram",
          "transport-bus",
          "transport-taxi",
          "transport-canoe",
          "transport-ferry",
          "transport-ship",
          "nature_weather-tree",
          "nature_weather-flower",
          "nature_weather-sun",
          "nature_weather-cloud",
          "nature_weather-leaf",
          "nature_weather-cactus",
          "nature_weather-rock",
          "nature_weather-grass",
          "clothing-shirt",
          "clothing-pants",
          "clothing-dress",
          "clothing-skirt",
          "clothing-socks",
          "clothing-shoes",
          "clothing-boots",
          "clothing-hat",
          "clothing-scarf",
          "home_furniture_bathroom-bed",
          "home_furniture_bathroom-table",
          "home_furniture_bathroom-chair",
          "home_furniture_bathroom-lamp",
          "home_furniture_bathroom-sofa",
          "home_furniture_bathroom-door",
          "home_furniture_bathroom-window",
          "home_furniture_bathroom-clock",
          "home_furniture_bathroom-mirror",
          "home_furniture_bathroom-soap",
          "home_furniture_bathroom-towel",
          "school_play-book",
          "school_play-pen",
          "school_play-glue",
          "school_play-school_bag",
          "school_play-kite",
          "school_play-ball",
          "school_play-gift",
          "kitchen_household-cup",
          "kitchen_household-mug",
          "kitchen_household-plate",
          "kitchen_household-bottle",
          "kitchen_household-fork",
          "kitchen_household-bowl",
          "kitchen_household-knife",
          "kitchen_household-milk",
          "kitchen_household-cheese",
          "kitchen_household-orange",
          "kitchen_household-rice",
          "kitchen_household-soup",
          "places_city_objects-house",
          "places_city_objects-school",
          "places_city_objects-store",
          "places_city_objects-park",
          "places_city_objects-bridge",
          "places_city_objects-key",
          "places_city_objects-phone",
          "places_city_objects-lock",
          "places_city_objects-tv",
          "places_city_objects-camera",
          "places_city_objects-box",
          "places_city_objects-balloon",
          "additional_animals-sheep",
          "additional_animals-donkey",
          "additional_animals-chick"
        ]
      },
      distractors: {
        minSimilarityScore: 1,
        maxSimilarityScore: 3,
        maxLengthDelta: 2,
        allowSameFirstLetter: true,
        allowSameLastLetter: true
      }
    },
    hard: {
      label: "Hard",
      maxFrequency: 3,
      maxWordLength: 7,
      minWordLength: 5,
      wordPool: {
        excludedCategories: ["legacy"]
      },
      distractors: {
        minSimilarityScore: 2,
        maxSimilarityScore: 5,
        maxLengthDelta: 2,
        allowSameFirstLetter: true,
        allowSameLastLetter: true,
        preferSameLength: true
      }
    },
    super: {
      label: "Super",
      maxFrequency: 4,
      maxWordLength: Infinity,
      minWordLength: 7,
      wordPool: {
        excludedCategories: ["legacy"]
      },
      distractors: {
        requireStrictDistractors: true,
        minSimilarityScore: 4,
        maxSimilarityScore: 8,
        maxLengthDelta: 1,
        allowSameFirstLetter: true,
        allowSameLastLetter: true,
        preferSameLength: true,
        preferSharedPrefixLength: 2,
        preferSharedSuffixLength: 2
      }
    }
  },
  gameplay: {
    normalAttempts: 2,
    specialAttempts: 1,
    specialChance: 1 / 6,
    specialSilverWeight: 70,
    specialGoldWeight: 25,
    specialDiamondWeight: 5,
    specialSilverCoins: 1,
    specialGoldCoins: 5,
    specialDiamondCoins: 20,
    baseSpeed: 96,
    speedIncPerLevel: 8,
    tileWidth: 360,
    tileHeight: 116,
    tileMargin: 10,
    sfxGain: 0.1,
    levelGoals: {
      easy: { correctTarget: 8, timeLimitMs: 60000 },
      medium: { correctTarget: 10, timeLimitMs: 75000 },
      hard: { correctTarget: 12, timeLimitMs: 90000 },
      super: { correctTarget: 14, timeLimitMs: 90000 }
    }
  }
};
